language: python
dist: trusty
services:
  - postgresql

before_script:
  - psql -c 'create database travisci;' -U postgres

before_install:
  - export DJANGO_SETTINGS_MODULE="settings.test"
  - export PYTHONPATH="$HOME/build/gnosis/gnosisdb"
  - export PIP_USE_MIRRORS=true

script:
  - cd gnosisdb
  - python manage.py test