language: python
dist: trusty
addons:
  ssh_known_hosts:
  - gnosisdb-beta.gnosis.pm
services:
- postgresql
before_script:
- psql -c 'create database travisci;' -U postgres
before_install:
- openssl aes-256-cbc -K $encrypted_1475ea0b013f_key -iv $encrypted_1475ea0b013f_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
- export DJANGO_SETTINGS_MODULE="settings.test"
- export PYTHONPATH="$HOME/build/gnosis/gnosisdb"
- export PIP_USE_MIRRORS=true
script:
- cd gnosisdb
- python manage.py test
after_success:
- cd ../
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- git remote add deploy dokku@gnosisdb-beta.gnosis.pm:gnosisdb-beta.gnosis.pm
- git push deploy master -f
