version: '2'
#networks:
#  testnet:
#    driver: bridge
#    ipam:
#      config:
#      - subnet: 172.25.0.0/24
services:
#  ipfs:
#    hostname: ipfs
#    image: jbenet/go-ipfs:latest
#    ports:
#      - "8080:8080"
#      - "4001:4001"
#      - "172.25.0.101:5001:5001"
#    volumes:
#      - ./.ipfs/:/data/ipfs/
#    networks:
#      testnet:
#        ipv4_address: 172.25.0.101
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=gnosisdb
      - RABBITMQ_DEFAULT_PASS=gnosisdb
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    links:
      - db
#      - ipfs
#    depends_on:
#      - ipfs
    working_dir: /gnosisdb/gnosisdb
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "27017"
      - "5432"
  worker:
    build:
      context: .
      dockerfile: DockerfileCelery
    command: sh run_celery.sh
    env_file:
      - .env
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
