version: '2'
services:
  db:
    image: postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
      - db
    ports:
      - "8080"
      - "27017"
  mongo:
    image: mongo:3.0.2
    ports:
      - "27017:27017"