version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
      - db
    ports:
      - "8000:8000"
      - "8080"
      - "27017"
      - "5432"
  mongo:
    image: mongo:3.0.2
    ports:
      - "27017:27017"
  db:
    image: postgres
    ports:
      - "5432:5432"
