version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    links:
      - mongo
      - db
    ports:
      - "8000:8000"
      - "8080"
      - "27017"
      - "5432"
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=gnosisdb
      - RABBITMQ_DEFAULT_PASS=gnosisdb
    ports:
      - "5672:5672"
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
  mongo:
    image: mongo:3.0.2
    ports:
      - "27017:27017"
  db:
    image: postgres
    ports:
      - "5432:5432"
